### PR TITLE
No agnostic line search

### PR DESCRIPTION
**Pull request by gdalle**
Testing the waters to see if #40 has been solved by the latest release of FrankWolfe mentioned in https://github.com/ZIB-IOL/FrankWolfe.jl/issues/387

### CODE REVIEW

**Comment by gdalle** [comment]
@matbesancon this still errors

**Comment by matbesancon** [comment]
Ah my bad I hadn't released the better error printing in case of NaNs. But this will improve the error message only, the underlying problem here seems to be with NaN elements in the gradient no?

**Comment by gdalle** [comment]
It's interesting that it works on 1.7 though

**Comment by matbesancon** [comment]
maybe you are not reaching the point where the gradient evaluates to NaN? The RNG in Julia changed from 1.7 onwards if I recall

**Comment by gdalle** [comment]
Possibly. Not sure how to debug this though, the MWE is pretty involved

**Comment by matbesancon** [comment]
one ugly way would be to print the gradient at every iteration, or print the direction in the LMO itself

**Comment by matbesancon** [comment]
let's debug that between main dish and dessert next week

**Pull request closed without merging**
